"""
Segmentation / Clustering.

Auto-discovers natural groups in the dataset's numeric measures via a
from-scratch k-means (numpy only -- no sklearn, consistent with the rest of
the app's "no external ML library" pattern already established in
correlation_center.py's VIF check). Nothing here is a new detection engine
in the insight_engine.py/weak_points.py sense -- it's a structural view of
the data (which rows tend to sit together across the measures) rather than
a rule about any single column, so it lives in its own module.

Two things this deliberately does NOT do, both on purpose:
- No silhouette/inertia jargon reaches the user -- clusters are described
  in the same plain-English style weak_points.py established ("High X,
  Low Y"), not "cluster 2, centroid distance 1.4".
- No LLM call to name or describe a cluster -- the label is generated by
  comparing each cluster's mean to the dataset's overall mean per measure,
  same rule-based spirit as everything else in this app.

Performance note, following the pattern set by the 150K-row fix documented
in HANDOFF.md (profile first, sample where the algorithm allows it without
changing the answer): fitting k-means is iterative and O(n * k * iters), so
centroids are fit on a capped random sample rather than the full dataset on
very large files. Every row is still assigned a segment afterward -- that
assignment step is a single vectorized distance computation, O(n * k), and
stays cheap even at 150K+ rows.
"""
from dataclasses import dataclass, field
import numpy as np
import pandas as pd

from app.understanding import DatasetProfile

MIN_MEASURES = 2
MAX_MEASURES = 6            # cap for interpretability/speed; primary measures first
MIN_USABLE_ROWS = 30        # below this, groups aren't reliable enough to show
MAX_FIT_SAMPLE = 5000       # rows used to fit centroids on large datasets
MAX_SILHOUETTE_SAMPLE = 800 # rows used to score candidate k values (pairwise distance = O(n^2))
MAX_SCATTER_POINTS = 400    # matches executor_v2.MAX_SCATTER_POINTS, same display cap

K_MIN, K_MAX = 2, 5
KMEANS_N_INIT = 5
KMEANS_MAX_ITER = 100
KMEANS_TOL = 1e-4
RANDOM_SEED = 42            # matches the random_state=42 used elsewhere (executor_v2, VIF)

TRAIT_Z_THRESHOLD = 0.35    # a measure has to differ from the overall average by at least
                             # this many standard deviations to be called out in the label


@dataclass
class SegmentTrait:
    measure: str
    direction: str   # "high" | "low"
    z: float


@dataclass
class Segment:
    id: str
    label: str
    description: str
    size: int
    pct: float
    averages: dict = field(default_factory=dict)
    traits: list = field(default_factory=list)  # list[SegmentTrait]


def _kmeans_plus_plus_init(X: np.ndarray, k: int, rng: np.random.Generator) -> np.ndarray:
    n = X.shape[0]
    centers = np.empty((k, X.shape[1]))
    first = rng.integers(n)
    centers[0] = X[first]
    closest_sq_dist = np.sum((X - centers[0]) ** 2, axis=1)
    for i in range(1, k):
        total = closest_sq_dist.sum()
        if total <= 0:
            # every remaining point is identical to an existing center --
            # just fill the rest with random distinct points.
            remaining = rng.choice(n, size=k - i, replace=False)
            centers[i:] = X[remaining]
            break
        probs = closest_sq_dist / total
        chosen = rng.choice(n, p=probs)
        centers[i] = X[chosen]
        new_sq_dist = np.sum((X - centers[i]) ** 2, axis=1)
        closest_sq_dist = np.minimum(closest_sq_dist, new_sq_dist)
    return centers


def _kmeans_once(X: np.ndarray, k: int, rng: np.random.Generator):
    """One full k-means run (init + Lloyd's algorithm). Returns
    (labels, centers, inertia), or None if it collapsed to fewer than k
    non-empty clusters (can happen with unlucky init on small/degenerate
    data -- the caller tries again with a different seed)."""
    centers = _kmeans_plus_plus_init(X, k, rng)
    labels = np.zeros(len(X), dtype=int)
    for _ in range(KMEANS_MAX_ITER):
        dists = np.linalg.norm(X[:, None, :] - centers[None, :, :], axis=2)
        new_labels = dists.argmin(axis=1)

        if set(np.unique(new_labels)) != set(range(k)):
            return None  # an empty cluster -- unusable run

        new_centers = np.array([X[new_labels == c].mean(axis=0) for c in range(k)])
        shift = np.linalg.norm(new_centers - centers)
        centers = new_centers
        labels = new_labels
        if shift < KMEANS_TOL:
            break

    dists = np.linalg.norm(X - centers[labels], axis=1)
    inertia = float(np.sum(dists ** 2))
    return labels, centers, inertia


def _fit_kmeans(X: np.ndarray, k: int, rng: np.random.Generator):
    """Runs k-means from several random starts, keeps the lowest-inertia
    result -- a single k-means++ init is good but not immune to landing in
    a worse local minimum than another start would find."""
    best = None
    for _ in range(KMEANS_N_INIT):
        result = _kmeans_once(X, k, rng)
        if result is None:
            continue
        if best is None or result[2] < best[2]:
            best = result
    return best


def _silhouette_score(X: np.ndarray, labels: np.ndarray) -> float:
    """Mean silhouette coefficient over X (already capped to a small sample
    by the caller -- this is O(n^2)). Higher is better-separated clusters."""
    n = len(X)
    dist = np.linalg.norm(X[:, None, :] - X[None, :, :], axis=2)
    scores = np.empty(n)
    for i in range(n):
        own = labels[i]
        same_mask = (labels == own)
        same_mask[i] = False
        if not same_mask.any():
            scores[i] = 0.0
            continue
        a = dist[i, same_mask].mean()
        others = [c for c in np.unique(labels) if c != own]
        b = min(dist[i, labels == c].mean() for c in others)
        scores[i] = (b - a) / max(a, b) if max(a, b) > 0 else 0.0
    return float(scores.mean())


def _choose_k(X: np.ndarray, rng: np.random.Generator):
    n = len(X)
    k_max = min(K_MAX, n - 1)
    if k_max < K_MIN:
        return None

    sil_idx = rng.choice(n, size=min(MAX_SILHOUETTE_SAMPLE, n), replace=False)
    X_sil = X[sil_idx]

    best_k, best_score, best_fit = None, -2.0, None
    for k in range(K_MIN, k_max + 1):
        fit = _fit_kmeans(X, k, rng)
        if fit is None:
            continue
        labels, centers, _inertia = fit
        score = _silhouette_score(X_sil, labels[sil_idx])
        if score > best_score:
            best_k, best_score, best_fit = k, score, fit
    if best_fit is None:
        return None
    return best_k, best_fit


def _pick_display_axes(X: np.ndarray, labels: np.ndarray, cols: list) -> tuple:
    """Picks the two measures that separate the clusters most clearly, via a
    simple between/within variance ratio (same spirit as an F-ratio) on the
    standardized values -- so the scatter people see is the one where the
    groups are actually visible, not just the first two columns."""
    if len(cols) <= 2:
        return cols[0], cols[1]

    overall_mean = X.mean(axis=0)
    k = labels.max() + 1
    between = np.zeros(X.shape[1])
    within = np.zeros(X.shape[1])
    for c in range(k):
        members = X[labels == c]
        if len(members) == 0:
            continue
        between += len(members) * (members.mean(axis=0) - overall_mean) ** 2
        within += np.sum((members - members.mean(axis=0)) ** 2, axis=0)
    ratio = between / np.where(within > 0, within, 1e-9)
    top2 = np.argsort(ratio)[::-1][:2]
    return cols[top2[0]], cols[top2[1]]


def _describe_segment(cluster_means: np.ndarray, overall_mean: np.ndarray, overall_std: np.ndarray, cols: list):
    """Rule-based, plain-English label: the 1-2 measures where this
    cluster's average differs most from the dataset's overall average,
    phrased as High/Low -- deliberately the same "no jargon" style
    weak_points.py established, not a statistical readout."""
    z = (cluster_means - overall_mean) / np.where(overall_std > 0, overall_std, 1e-9)
    order = np.argsort(-np.abs(z))
    traits = []
    for idx in order:
        if abs(z[idx]) < TRAIT_Z_THRESHOLD:
            continue
        traits.append(SegmentTrait(measure=cols[idx], direction="high" if z[idx] > 0 else "low", z=float(z[idx])))
        if len(traits) == 2:
            break

    if not traits:
        label = "Average Across the Board"
        description = "This group doesn't stand out on any single measure -- it sits close to the overall average on all of them."
    else:
        label = " · ".join(f"{'High' if t.direction == 'high' else 'Low'} {t.measure}" for t in traits)
        parts = [f"{'above-average' if t.direction == 'high' else 'below-average'} {t.measure}" for t in traits]
        description = f"Stands out for {' and '.join(parts)} compared to the rest of the dataset."

    return label, description, traits


def analyze_segments(df: pd.DataFrame, profile: DatasetProfile) -> dict:
    all_cols = [m.column for m in profile.measures]
    cols = all_cols[:MAX_MEASURES]
    truncated_note = (
        f"Limited to the {MAX_MEASURES} most relevant measures ({', '.join(cols)}) out of "
        f"{len(all_cols)} -- more than that stops being visually meaningful on a 2D chart."
        if len(all_cols) > MAX_MEASURES else None
    )

    if len(cols) < MIN_MEASURES:
        return {"available": False, "note": "Needs at least two numeric measures to look for natural groups in the data."}

    usable = df[cols].dropna()
    usable = usable.loc[:, usable.std(ddof=0) > 0]  # constant columns can't separate anything
    cols = list(usable.columns)
    if len(cols) < MIN_MEASURES:
        return {"available": False, "note": "The numeric measures here don't vary enough to form meaningful groups."}
    if len(usable) < MIN_USABLE_ROWS:
        return {"available": False, "note": f"Only {len(usable)} rows have complete data across these measures -- not enough to find reliable groups."}

    overall_mean = usable.mean().to_numpy()
    overall_std = usable.std(ddof=0).to_numpy()
    X_full = ((usable.to_numpy(dtype=float) - overall_mean) / np.where(overall_std > 0, overall_std, 1e-9))

    rng = np.random.default_rng(RANDOM_SEED)
    sampled_for_fit = len(X_full) > MAX_FIT_SAMPLE
    if sampled_for_fit:
        fit_idx = rng.choice(len(X_full), size=MAX_FIT_SAMPLE, replace=False)
        X_fit = X_full[fit_idx]
    else:
        X_fit = X_full

    chosen = _choose_k(X_fit, rng)
    if chosen is None:
        return {"available": False, "note": "Couldn't find stable, well-separated groups in this data."}
    k, (fit_labels, centers, _inertia) = chosen

    # Assign every row (not just the fit sample) to its nearest centroid --
    # a single vectorized distance computation, cheap even at 150K+ rows.
    dists = np.linalg.norm(X_full[:, None, :] - centers[None, :, :], axis=2)
    all_labels = dists.argmin(axis=1)

    x_col, y_col = _pick_display_axes(X_full, all_labels, cols)

    usable = usable.reset_index(drop=True)
    counts = np.bincount(all_labels, minlength=k)
    order = np.argsort(-counts)  # biggest group first, for a stable "Segment 1" = largest

    clusters = []
    id_for_raw_label = {}
    for display_i, raw_label in enumerate(order):
        members = usable[all_labels == raw_label]
        cluster_means = members.mean().to_numpy()
        label, description, traits = _describe_segment(cluster_means, overall_mean, overall_std, cols)
        seg_id = f"segment_{display_i + 1}"
        id_for_raw_label[raw_label] = seg_id
        clusters.append(Segment(
            id=seg_id,
            label=f"Segment {display_i + 1}: {label}",
            description=description,
            size=int(counts[raw_label]),
            pct=round(100 * counts[raw_label] / len(usable), 1),
            averages={c: round(float(v), 3) for c, v in zip(cols, cluster_means)},
            traits=traits,
        ))

    # Display sample -- capped like every other scatter in the app.
    n_points = len(usable)
    if n_points > MAX_SCATTER_POINTS:
        display_idx = rng.choice(n_points, size=MAX_SCATTER_POINTS, replace=False)
    else:
        display_idx = np.arange(n_points)

    scatter_points = [
        {
            "x": float(usable.iloc[i][x_col]),
            "y": float(usable.iloc[i][y_col]),
            "group": id_for_raw_label[all_labels[i]],
        }
        for i in display_idx
    ]
    # Swap in the human label for each group id so the legend/tooltip reads
    # naturally, without a separate id-to-label lookup on the frontend.
    label_by_id = {c.id: c.label.split(": ", 1)[0] for c in clusters}  # "Segment 1"
    for p in scatter_points:
        p["group"] = label_by_id[p["group"]]

    note = truncated_note
    if sampled_for_fit:
        sample_note = f"Groups were fit on a random sample of {MAX_FIT_SAMPLE:,} rows for speed, then every row was assigned to its nearest group."
        note = f"{note} {sample_note}" if note else sample_note

    return {
        "available": True,
        "k": k,
        "measures_used": cols,
        "x_measure": x_col,
        "y_measure": y_col,
        "row_count_used": len(usable),
        "clusters": clusters,
        "scatter_points": scatter_points,
        "note": note,
    }
