// Builds a plain-text summary of an analysis result for pasting into
// Slack, email, or anywhere else that doesn't render markdown/HTML.
// Runs entirely client-side -- no network call, nothing sent to the
// backend, consistent with the "nothing is persisted" design already
// used by exportReport.js's Excel export.

const CURRENCY_HINTS = ['sale', 'revenue', 'price', 'cost', 'amount', 'fare', 'profit', 'value', 'income', 'pay', 'earning', 'billing', 'salary'];
const KPI_BLACKLIST = ['row_count', 'column_count', 'data_completeness_pct', 'date_range'];
const MAX_KPIS = 6;
const MAX_FINDINGS = 5;
const MAX_WEAK_POINTS = 2;

function humanizeKpiKey(key) {
  const isPercent = key.endsWith('_pct');
  const base = isPercent ? key.slice(0, -4) : key;
  const label = base.split('_').map((w) => w[0].toUpperCase() + w.slice(1)).join(' ');
  return { label, isPercent };
}

function formatKpiValue(key, value, isPercent) {
  if (typeof value !== 'number') return String(value);
  if (isPercent) return `${value.toFixed(1)}%`;
  const isCurrency = CURRENCY_HINTS.some((k) => key.toLowerCase().includes(k));
  const formatted = value.toLocaleString('en-US', { maximumFractionDigits: 2 });
  return isCurrency ? `$${formatted}` : formatted;
}

export function buildFindingsText(session) {
  const result = session.result;
  const v2 = result?.v2;
  if (!v2) return '';

  const lines = [];
  const profile = v2.profile || {};

  lines.push(`DataLens Summary — ${session.fileName}`);
  const metaBits = [profile.domain, profile.row_count ? `${profile.row_count.toLocaleString()} rows` : null, new Date().toLocaleDateString()].filter(Boolean);
  lines.push(metaBits.join(' · '));
  lines.push('');

  // --- Key Metrics ---
  const kpis = result?.kpis || {};
  const kpiEntries = Object.entries(kpis).filter(([k]) => !KPI_BLACKLIST.includes(k)).slice(0, MAX_KPIS);
  if (kpiEntries.length) {
    lines.push('KEY METRICS');
    for (const [key, value] of kpiEntries) {
      const { label, isPercent } = humanizeKpiKey(key);
      lines.push(`• ${label}: ${formatKpiValue(key, value, isPercent)}`);
    }
    lines.push('');
  }

  // --- The Story ---
  if (v2.story?.length) {
    lines.push('THE STORY');
    for (const beat of v2.story) {
      lines.push(`${beat.label}: ${beat.text}`);
    }
    lines.push('');
  }

  // --- Top Findings ---
  if (v2.findings?.length) {
    lines.push('TOP FINDINGS');
    const sorted = [...v2.findings].sort((a, b) => (b.score || 0) - (a.score || 0)).slice(0, MAX_FINDINGS);
    sorted.forEach((f, i) => lines.push(`${i + 1}. ${f.text}`));
    lines.push('');
  }

  // --- Segments (if available) ---
  if (v2.segments?.available && v2.segments.clusters?.length) {
    const top = [...v2.segments.clusters].sort((a, b) => b.pct - a.pct)[0];
    lines.push(`SEGMENTS: ${v2.segments.k} natural groups found — largest is "${top.label.replace(/^Segment \d+: /, '')}" at ${top.pct}%.`);
    lines.push('');
  }

  // --- Seasonality (if available) ---
  if (v2.seasonality?.available) {
    lines.push(`SEASONALITY: ${v2.seasonality.summary}`);
    lines.push('');
  }

  // --- Weak Points (high priority only, keep it lightweight) ---
  const highPriority = (v2.weak_points || []).filter((w) => w.priority === 'high').slice(0, MAX_WEAK_POINTS);
  if (highPriority.length) {
    lines.push('WATCH');
    for (const w of highPriority) {
      lines.push(`⚠ ${w.problem}`);
      if (w.suggested_action) lines.push(`   → ${w.suggested_action}`);
    }
    lines.push('');
  }

  // --- Data Quality ---
  if (v2.data_quality?.overall_quality_score != null) {
    lines.push(`Data quality: ${Math.round(v2.data_quality.overall_quality_score)}/100`);
  }

  lines.push('—');
  lines.push('Generated by DataLens · rule-based, no AI calls · nothing stored');

  return lines.join('\n');
}
